baseURL = 'https://bodrovis.tech/'
languageCode = 'en-us'
title = 'Ilya Krukowski'

enableRobotsTXT = true

# disableKinds = ["taxonomy"]

paginate = 15

markup.highlight.noClasses=false

[taxonomies]
tag = "tags"
category = "blog"

[markup.goldmark.renderer]
unsafe = true