baseURL = 'https://bodrovis.tech/'
locale = 'en-us'
title = 'Ilya Krukowski'

enableRobotsTXT = true

[params]
description = "Ilya Krukowski (bodrovis) website. Articles about web, programming, crypto, abstract algebra, and more."
meta_image = "og-image.png"

[pagination]
pagerSize = 15

[markup]
[markup.highlight]
noClasses = false

[taxonomies]
tag = "tags"
category = "blog"

[markup.goldmark.renderer]
unsafe = true