baseURL = 'https://bodrovis.tech/'
languageCode = 'en-us'
title = 'Ilya Krukowski'

enableRobotsTXT = true

[pagination]
pagerSize = 15

[markup]
[markup.highlight]
noClasses = false

[taxonomies]
tag = "tags"
category = "blog"

[markup.goldmark.renderer]
unsafe = true